### PR TITLE
Toc directive

### PR DESCRIPTION
**Pull request by AakashGfude**
Hey @choldgraf , have corrected tests for the toc directive. It seems to be working well. 
One thing to note is that the toctree in the page created by `add_toctree` :- https://github.com/choldgraf/jupyter-book/blob/master/jupyter_book/toc.py#L39 , does not have `sections` in it. So, the toc directive does not show sections. We can create a new PR for that.

### CODE REVIEW

**Comment by choldgraf** [comment]
Thanks for the improvement! Lemme rebase my branch so it's easier to see the diff. Could you explain a bit more what you mean by "does not have `sections`"?

**Comment by choldgraf** [comment]
actually these changes look good to me so let's just merge it and see how things look in the main PR :-)

**Comment by AakashGfude** [comment]
> Thanks for the improvement! Lemme rebase my branch so it's easier to see the diff. Could you explain a bit more what you mean by "does not have `sections`"?

I meant the entries inside the `sections` part of a `file` in `_toc.yml`

**Comment by choldgraf** [comment]
ah - right let's figure that out in the main PR

**Pull request merged**
